version: '3.6'

services:
  fdb:
    image: foundationdb/foundationdb:7.1.23
    environment:
      FDB_NETWORKING_MODE: container
      FDB_COORDINATOR_PORT: 4500
      FDB_COORDINATOR: fdb
      FDB_PORT: 4500
  storage:
    image: minecpp/storage:latest
    volumes:
      - '.:/config'
    environment:
      PORT: 7000
      CLUSTERFILE_PATH: "/config/clusterfile-docker"
    command: bash -c "/config/docker/init_database.sh && /usr/bin/minecpp_storage"
    depends_on:
      - fdb
  engine:
    image: minecpp/engine:latest
    volumes:
      - '.:/config'
    environment:
      CONFIG_FILE: /config/service/engine/config-docker.yaml
    command: bash -c "sleep 3 && /usr/bin/minecpp_engine"
    depends_on:
      - storage
  front:
    image: minecpp/front:latest
    volumes:
      - '.:/config'
    environment:
      CONFIG_FILE: /config/service/front/config-docker.yaml
      PORT: 25565
    command: bash -c "openssl genrsa -out /var/minecpp_key.pem 1024 && sleep 4 && /usr/bin/minecpp_front"
    ports:
      - "25565:25565"
    depends_on:
      - engine
