server:
  bind_address: "0.0.0.0"
  bind_port: 7101
engine:
  endpoints:
    - "localhost:7800"
  strategy: round_robin
encryption:
  enabled: true
debug_logger: true
resources:
  registry: "registry.bin"
