// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: minecpp/proto/service/engine/v1/engine.proto

#include <minecpp/proto/service/engine/v1/engine.pb.h>

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace minecpp {
namespace proto {
namespace service {
namespace engine {
namespace v1 {
}  // namespace v1
}  // namespace engine
}  // namespace service
}  // namespace proto
}  // namespace minecpp
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto = nullptr;
const uint32_t TableStruct_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n,minecpp/proto/service/engine/v1/engine"
  ".proto\022\037minecpp.proto.service.engine.v1\032"
  "4minecpp/proto/event/clientbound/v1/clie"
  "ntbound.proto\0324minecpp/proto/event/serve"
  "rbound/v1/serverbound.proto2q\n\rEngineSer"
  "vice\022`\n\004Join\022).minecpp.proto.event.serve"
  "rbound.v1.Event\032).minecpp.proto.event.cl"
  "ientbound.v1.Event(\0010\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto_deps[2] = {
  &::descriptor_table_minecpp_2fproto_2fevent_2fclientbound_2fv1_2fclientbound_2eproto,
  &::descriptor_table_minecpp_2fproto_2fevent_2fserverbound_2fv1_2fserverbound_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto = {
  false, false, 310, descriptor_table_protodef_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto, "minecpp/proto/service/engine/v1/engine.proto", 
  &descriptor_table_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto_once, descriptor_table_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto::offsets,
  nullptr, file_level_enum_descriptors_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto, file_level_service_descriptors_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto_getter() {
  return &descriptor_table_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto(&descriptor_table_minecpp_2fproto_2fservice_2fengine_2fv1_2fengine_2eproto);
namespace minecpp {
namespace proto {
namespace service {
namespace engine {
namespace v1 {

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace engine
}  // namespace service
}  // namespace proto
}  // namespace minecpp
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
