#include "block.h"

namespace Game::Block {

const Properties stone{
    .material = &Material::Rock,
    .color = ColorId::Stone,
    .hardness = 1.5f,
    .resistance = 6.0f,
};

const Properties bricks{
    .material = &Material::Rock,
    .color = ColorId::Red,
    .hardness = 2.0f,
    .resistance = 6.0f,
};

const Properties oak_planks{
    .material = &Material::Wood,
    .color = ColorId::Wood,
    .hardness = 2.0f,
    .resistance = 3.0f,
};

const Properties spruce_planks{
    .material = &Material::Wood,
    .color = ColorId::Obsidian,
    .hardness = 2.0f,
    .resistance = 3.0f,
};

const Properties birch_planks{
    .material = &Material::Wood,
    .color = ColorId::Sand,
    .hardness = 2.0f,
    .resistance = 3.0f,
};

const Properties jungle_planks{
    .material = &Material::Wood,
    .color = ColorId::Dirt,
    .hardness = 2.0f,
    .resistance = 3.0f,
};

const Properties acacia_planks{
    .material = &Material::Wood,
    .color = ColorId::Adobe,
    .hardness = 2.0f,
    .resistance = 3.0f,
};

const Properties dark_oak_planks{
    .material = &Material::Wood,
    .color = ColorId::Brown,
    .hardness = 2.0f,
    .resistance = 3.0f,
};

const Properties cobblestone{
    .material = &Material::Rock,
    .color = ColorId::Stone,
    .hardness = 2.0f,
    .resistance = 6.0f,
};

const Properties polished_granite{
    .material = &Material::Rock,
    .color = ColorId::Dirt,
    .hardness = 1.5f,
    .resistance = 6.0f,
};
const Properties smooth_red_sandstone{
    .material = &Material::Rock,
    .color = ColorId::Adobe,
    .hardness = 2.0f,
    .resistance = 6.0f,
};
const Properties mossy_stone_bricks{
    .material = &Material::Rock,
    .color = ColorId::Stone,
    .hardness = 1.5f,
    .resistance = 6.0f,
};
const Properties polished_diorite{
    .material = &Material::Rock,
    .color = ColorId::Quartz,
    .hardness = 1.5f,
    .resistance = 6.0f,
};
const Properties mossy_cobblestone{
    .material = &Material::Rock,
    .color = ColorId::Stone,
    .hardness = 2.0f,
    .resistance = 6.0f,
};
const Properties smooth_sandstone{
    .material = &Material::Rock,
    .color = ColorId::Sand,
    .hardness = 2.0f,
    .resistance = 6.0f,
};

const Properties smooth_quartz{
    .material = &Material::Rock,
    .color = ColorId::Quartz,
    .hardness = 2.0f,
    .resistance = 6.0f,
};

const Properties granite{
    .material = &Material::Rock,
    .color = ColorId::Dirt,
    .hardness = 1.5f,
    .resistance = 6.0f,
};

const Properties sandstone{
    .material = &Material::Rock,
    .color = ColorId::Sand,
    .hardness = 0.8f,
    .resistance = 0.8f,
};

const Properties andesite{
    .material = &Material::Rock,
    .color = ColorId::Stone,
    .hardness = 1.5f,
    .resistance = 6.0f,
};

const Properties red_nether_bricks{
    .material = &Material::Rock,
    .color = ColorId::Netherrack,
    .hardness = 2.0f,
    .resistance = 6.0f,
};

const Properties polished_andesite{
    .material = &Material::Rock,
    .color = ColorId::Stone,
    .hardness = 1.5f,
    .resistance = 6.0f,
};

const Properties diorite{
    .material = &Material::Rock,
    .color = ColorId::Quartz,
    .hardness = 1.5f,
    .resistance = 6.0f,
};

const Properties prismarine{
    .material = &Material::Rock,
    .color = ColorId::Cyan,
    .hardness = 1.5f,
    .resistance = 6.0f,
};

const Properties dark_prismarine{
    .material = &Material::Rock,
    .color = ColorId::Diamond,
    .hardness = 1.5f,
    .resistance = 6.0f,
};

const Properties red_sandstone{
    .material = &Material::Rock,
    .color = ColorId::Adobe,
    .hardness = 0.8f,
    .resistance = 1.0f,
};

const Properties stone_bricks{
    .material = &Material::Rock,
    .color = ColorId::Stone,
    .hardness = 1.5f,
    .resistance = 6.0f,
};

const Properties nether_bricks{
    .material = &Material::Rock,
    .color = ColorId::Netherrack,
    .hardness = 2.0f,
    .resistance = 6.0f,
};

const Properties quartz_block{
    .material = &Material::Rock,
    .color = ColorId::Quartz,
    .hardness = 0.8f,
    .resistance = 0.8f,
};

const Properties purpur_block{
    .material = &Material::Rock,
    .color = ColorId::Magenta,
    .hardness = 1.5f,
    .resistance = 6.0f,
};

const Properties prismarine_bricks{
    .material = &Material::Rock,
    .color = ColorId::Diamond,
    .hardness = 1.5f,
    .resistance = 6.0f,
};

const Properties end_stone_bricks{
    .material = &Material::Rock,
    .color = ColorId::Sand,
    .hardness = 3.0f,
    .resistance = 9.0f,
};

std::array<Block, 680> blocks{
   Block ("air", with_material(&Material::Air), with_does_not_block_movement(), with_no_drop()),
   Block ("stone", with_material(&Material::Rock, ColorId::Stone), with_durability(1.5F, 6.0F)),
   Block ("granite", with_material(&Material::Rock, ColorId::Dirt), with_durability(1.5F, 6.0F)),
   Block ("polished_granite", with_material(&Material::Rock, ColorId::Dirt), with_durability(1.5F, 6.0F)),
   Block ("diorite", with_material(&Material::Rock, ColorId::Quartz), with_durability(1.5F, 6.0F)),
   Block ("polished_diorite", with_material(&Material::Rock, ColorId::Quartz), with_durability(1.5F, 6.0F)),
   Block ("andesite", with_material(&Material::Rock, ColorId::Stone), with_durability(1.5F, 6.0F)),
   Block ("polished_andesite", with_material(&Material::Rock, ColorId::Stone), with_durability(1.5F, 6.0F)),
   Block ("grass_block", with_material(&Material::Organic), with_ticks_randomly(), with_durability(0.6F)),
   Block ("dirt", with_material(&Material::Earth, ColorId::Dirt), with_durability(0.5F)),
   Block ("coarse_dirt", with_material(&Material::Earth, ColorId::Dirt), with_durability(0.5F)),
   Block ("podzol", with_material(&Material::Earth, ColorId::Obsidian), with_durability(0.5F)),
   Block ("cobblestone", with_properties(cobblestone)),
   Block ("oak_planks", with_properties(oak_planks)),
   Block ("spruce_planks", with_properties(spruce_planks)),
   Block ("birch_planks", with_properties(birch_planks)),
   Block ("jungle_planks", with_properties(jungle_planks)),
   Block ("acacia_planks", with_properties(acacia_planks)),
   Block ("dark_oak_planks", with_properties(dark_oak_planks)),
   Block ("oak_sapling", with_material(&Material::Plants), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability()),
   Block ("spruce_sapling", with_material(&Material::Plants), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability()),
   Block ("birch_sapling", with_material(&Material::Plants), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability()),
   Block ("jungle_sapling", with_material(&Material::Plants), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability()),
   Block ("acacia_sapling", with_material(&Material::Plants), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability()),
   Block ("dark_oak_sapling", with_material(&Material::Plants), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability()),
   Block ("bedrock", with_material(&Material::Rock), with_durability(-1.0F, 3600000.0F), with_no_drop()),
   Block ("water", with_material(&Material::Water), with_does_not_block_movement(), with_durability(100.0F), with_no_drop()),
   Block ("lava", with_material(&Material::Lava), with_does_not_block_movement(), with_ticks_randomly(), with_durability(100.0F), with_light_value(15), with_no_drop()),
   Block ("sand",  with_material(&Material::Sand, ColorId::Sand), with_durability(0.5F)),
   Block ("red_sand", with_material(&Material::Sand, ColorId::Adobe), with_durability(0.5F)),
   Block ("gravel", with_material(&Material::Sand, ColorId::Stone), with_durability(0.6F)),
   Block ("gold_ore", with_material(&Material::Rock), with_durability(3.0F, 3.0F)),
   Block ("iron_ore", with_material(&Material::Rock), with_durability(3.0F, 3.0F)),
   Block ("coal_ore", with_material(&Material::Rock), with_durability(3.0F, 3.0F)),
   Block ("oak_log", with_material(&Material::Wood, ColorId::Obsidian), with_durability(2.0F)),
   Block ("spruce_log", with_material(&Material::Wood, ColorId::Brown), with_durability(2.0F)),
   Block ("birch_log", with_material(&Material::Wood, ColorId::Quartz), with_durability(2.0F)),
   Block ("jungle_log", with_material(&Material::Wood, ColorId::Obsidian), with_durability(2.0F)),
   Block ("acacia_log", with_material(&Material::Wood, ColorId::Stone), with_durability(2.0F)),
   Block ("dark_oak_log", with_material(&Material::Wood, ColorId::Brown), with_durability(2.0F)),
   Block ("stripped_spruce_log", with_material(&Material::Wood, ColorId::Obsidian), with_durability(2.0F)),
   Block ("stripped_birch_log", with_material(&Material::Wood, ColorId::Sand), with_durability(2.0F)),
   Block ("stripped_jungle_log", with_material(&Material::Wood, ColorId::Dirt), with_durability(2.0F)),
   Block ("stripped_acacia_log", with_material(&Material::Wood, ColorId::Adobe), with_durability(2.0F)),
   Block ("stripped_dark_oak_log", with_material(&Material::Wood, ColorId::Brown), with_durability(2.0F)),
   Block ("stripped_oak_log", with_material(&Material::Wood, ColorId::Wood), with_durability(2.0F)),
   Block ("oak_wood", with_material(&Material::Wood, ColorId::Wood), with_durability(2.0F)),
   Block ("spruce_wood", with_material(&Material::Wood, ColorId::Obsidian), with_durability(2.0F)),
   Block ("birch_wood", with_material(&Material::Wood, ColorId::Sand), with_durability(2.0F)),
   Block ("jungle_wood", with_material(&Material::Wood, ColorId::Dirt), with_durability(2.0F)),
   Block ("acacia_wood", with_material(&Material::Wood, ColorId::Gray), with_durability(2.0F)),
   Block ("dark_oak_wood", with_material(&Material::Wood, ColorId::Brown), with_durability(2.0F)),
   Block ("stripped_oak_wood", with_material(&Material::Wood, ColorId::Wood), with_durability(2.0F)),
   Block ("stripped_spruce_wood", with_material(&Material::Wood, ColorId::Obsidian), with_durability(2.0F)),
   Block ("stripped_birch_wood", with_material(&Material::Wood, ColorId::Sand), with_durability(2.0F)),
   Block ("stripped_jungle_wood", with_material(&Material::Wood, ColorId::Dirt), with_durability(2.0F)),
   Block ("stripped_acacia_wood", with_material(&Material::Wood, ColorId::Adobe), with_durability(2.0F)),
   Block ("stripped_dark_oak_wood", with_material(&Material::Wood, ColorId::Brown), with_durability(2.0F)),
   Block ("oak_leaves", with_material(&Material::Leaves), with_durability(0.2F), with_ticks_randomly(), with_not_solid()),
   Block ("spruce_leaves", with_material(&Material::Leaves), with_durability(0.2F), with_ticks_randomly(), with_not_solid()),
   Block ("birch_leaves", with_material(&Material::Leaves), with_durability(0.2F), with_ticks_randomly(), with_not_solid()),
   Block ("jungle_leaves", with_material(&Material::Leaves), with_durability(0.2F), with_ticks_randomly(), with_not_solid()),
   Block ("acacia_leaves", with_material(&Material::Leaves), with_durability(0.2F), with_ticks_randomly(), with_not_solid()),
   Block ("dark_oak_leaves", with_material(&Material::Leaves), with_durability(0.2F), with_ticks_randomly(), with_not_solid()),
   Block ("sponge", with_material(&Material::Sponge), with_durability(0.6F)),
   Block ("wet_sponge", with_material(&Material::Sponge), with_durability(0.6F)),
   Block ("glass", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("lapis_ore", with_material(&Material::Rock), with_durability(3.0F, 3.0F)),
   Block ("lapis_block", with_material(&Material::Iron, ColorId::Lapis), with_durability(3.0F, 3.0F)),
   Block ("dispenser", with_material(&Material::Rock), with_durability(3.5F)),
   Block ("sandstone", with_material(&Material::Rock, ColorId::Sand), with_durability(0.8F)),
   Block ("chiseled_sandstone", with_material(&Material::Rock, ColorId::Sand), with_durability(0.8F)),
   Block ("cut_sandstone", with_material(&Material::Rock, ColorId::Sand), with_durability(0.8F)),
   Block ("note_block", with_material(&Material::Wood), with_durability(0.8F)),
   Block ("white_bed", with_material(&Material::Wool), with_durability(0.2F), with_not_solid()),
   Block ("orange_bed", with_material(&Material::Wool), with_durability(0.2F), with_not_solid()),
   Block ("magenta_bed",  with_material(&Material::Wool), with_durability(0.2F), with_not_solid()),
   Block ("light_blue_bed", with_material(&Material::Wool), with_durability(0.2F), with_not_solid()),
   Block ("yellow_bed", with_material(&Material::Wool), with_durability(0.2F), with_not_solid()),
   Block ("lime_bed", with_material(&Material::Wool), with_durability(0.2F), with_not_solid()),
   Block ("pink_bed", with_material(&Material::Wool), with_durability(0.2F), with_not_solid()),
   Block ("gray_bed", with_material(&Material::Wool), with_durability(0.2F), with_not_solid()),
   Block ("light_gray_bed", with_material(&Material::Wool), with_durability(0.2F), with_not_solid()),
   Block ("cyan_bed", with_material(&Material::Wool), with_durability(0.2F), with_not_solid()),
   Block ("purple_bed", with_material(&Material::Wool), with_durability(0.2F), with_not_solid()),
   Block ("blue_bed", with_material(&Material::Wool), with_durability(0.2F), with_not_solid()),
   Block ("brown_bed", with_material(&Material::Wool), with_durability(0.2F), with_not_solid()),
   Block ("green_bed", with_material(&Material::Wool), with_durability(0.2F), with_not_solid()),
   Block ("red_bed", with_material(&Material::Wool), with_durability(0.2F), with_not_solid()),
   Block ("black_bed", with_material(&Material::Wool), with_durability(0.2F), with_not_solid()),
   Block ("powered_rail", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_durability(0.7F)),
   Block ("detector_rail", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_durability(0.7F)),
   Block ("sticky_piston", with_material(&Material::Piston), with_durability(0.5F)),
   Block ("cobweb", with_material(&Material::Web), with_does_not_block_movement(), with_durability(4.0F)),
   Block ("grass", with_material(&Material::TallPlants), with_does_not_block_movement(), with_zero_durability()),
   Block ("fern", with_material(&Material::TallPlants), with_does_not_block_movement(), with_zero_durability()),
   Block ("dead_bush", with_material(&Material::TallPlants, ColorId::Wood), with_does_not_block_movement(), with_zero_durability()),
   Block ("seagrass", with_material(&Material::SeaGrass), with_does_not_block_movement(), with_zero_durability()),
   Block ("tall_seagrass", with_material(&Material::SeaGrass), with_does_not_block_movement(), with_zero_durability()),
   Block ("piston", with_material(&Material::Piston), with_durability(0.5F)),
   Block ("piston_head", with_material(&Material::Piston), with_durability(0.5F), with_no_drop()),
   Block ("white_wool", with_material(&Material::Wool, ColorId::Snow), with_durability(0.8F)),
   Block ("orange_wool", with_material(&Material::Wool, ColorId::Adobe), with_durability(0.8F)),
   Block ("magenta_wool", with_material(&Material::Wool, ColorId::Magenta), with_durability(0.8F)),
   Block ("light_blue_wool", with_material(&Material::Wool, ColorId::LightBlue), with_durability(0.8F)),
   Block ("yellow_wool", with_material(&Material::Wool, ColorId::Yellow), with_durability(0.8F)),
   Block ("lime_wool", with_material(&Material::Wool, ColorId::Lime), with_durability(0.8F)),
   Block ("pink_wool", with_material(&Material::Wool, ColorId::Pink), with_durability(0.8F)),
   Block ("gray_wool", with_material(&Material::Wool, ColorId::Gray), with_durability(0.8F)),
   Block ("light_gray_wool", with_material(&Material::Wool, ColorId::LightGray), with_durability(0.8F)),
   Block ("cyan_wool", with_material(&Material::Wool, ColorId::Cyan), with_durability(0.8F)),
   Block ("purple_wool", with_material(&Material::Wool, ColorId::Purple), with_durability(0.8F)),
   Block ("blue_wool", with_material(&Material::Wool, ColorId::Blue), with_durability(0.8F)),
   Block ("brown_wool", with_material(&Material::Wool, ColorId::Brown), with_durability(0.8F)),
   Block ("green_wool", with_material(&Material::Wool, ColorId::Green), with_durability(0.8F)),
   Block ("red_wool", with_material(&Material::Wool, ColorId::Red), with_durability(0.8F)),
   Block ("black_wool", with_material(&Material::Wool, ColorId::Black), with_durability(0.8F)),
   Block ("moving_piston", with_material(&Material::Piston), with_durability(-1.0F), with_variable_opacity(), with_no_drop(), with_not_solid()),
   Block ("dandelion", with_material(&Material::Plants), with_does_not_block_movement(), with_zero_durability()),
   Block ("poppy", with_material(&Material::Plants), with_does_not_block_movement(), with_zero_durability()),
   Block ("blue_orchid", with_material(&Material::Plants), with_does_not_block_movement(), with_zero_durability()),
   Block ("allium", with_material(&Material::Plants), with_does_not_block_movement(), with_zero_durability()),
   Block ("azure_bluet", with_material(&Material::Plants), with_does_not_block_movement(), with_zero_durability()),
   Block ("red_tulip", with_material(&Material::Plants), with_does_not_block_movement(), with_zero_durability()),
   Block ("orange_tulip", with_material(&Material::Plants), with_does_not_block_movement(), with_zero_durability()),
   Block ("white_tulip", with_material(&Material::Plants), with_does_not_block_movement(), with_zero_durability()),
   Block ("pink_tulip", with_material(&Material::Plants), with_does_not_block_movement(), with_zero_durability()),
   Block ("oxeye_daisy", with_material(&Material::Plants), with_does_not_block_movement(), with_zero_durability()),
   Block ("cornflower", with_material(&Material::Plants), with_does_not_block_movement(), with_zero_durability()),
   Block ("wither_rose", with_material(&Material::Plants), with_does_not_block_movement(), with_zero_durability()),
   Block ("lily_of_the_valley", with_material(&Material::Plants), with_does_not_block_movement(), with_zero_durability()),
   Block ("brown_mushroom", with_material(&Material::Plants), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability(), with_light_value(1)),
   Block ("red_mushroom", with_material(&Material::Plants), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability()),
   Block ("gold_block", with_material(&Material::Iron, ColorId::Gold), with_durability(3.0F, 6.0F)),
   Block ("iron_block", with_material(&Material::Iron, ColorId::Iron), with_durability(5.0F, 6.0F)),
   Block ("bricks", with_properties(bricks)),
   Block ("tnt", with_material(&Material::Tnt), with_zero_durability()),
   Block ("bookshelf", with_material(&Material::Wood), with_durability(1.5F)),
   Block ("mossy_cobblestone", with_material(&Material::Rock), with_durability(2.0F, 6.0F)),
   Block ("obsidian", with_material(&Material::Rock, ColorId::Black), with_durability(50.0F, 1200.0F)),
   Block ("torch", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_zero_durability(), with_light_value(14)),
   Block ("wall_torch", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_zero_durability(), with_light_value(14), with_loot("torch")),
   Block ("fire", with_material(&Material::Fire, ColorId::Tnt), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability(), with_light_value(15), with_no_drop()),
   Block ("spawner", with_material(&Material::Rock), with_durability(5.0F), with_not_solid()),
   Block ("oak_stairs", with_properties(oak_planks)),
   Block ("chest", with_material(&Material::Wood), with_durability(2.5F)),
   Block ("redstone_wire", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_zero_durability()),
   Block ("diamond_ore", with_material(&Material::Rock), with_durability(3.0F, 3.0F)),
   Block ("diamond_block", with_material(&Material::Iron, ColorId::Diamond), with_durability(5.0F, 6.0F)),
   Block ("crafting_table", with_material(&Material::Wood), with_durability(2.5F)),
   Block ("wheat", with_material(&Material::Plants), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability()),
   Block ("farmland", with_material(&Material::Earth), with_ticks_randomly(), with_durability(0.6F)),
   Block ("furnace", with_material(&Material::Rock), with_durability(3.5F), with_light_value(13)),
   Block ("oak_sign", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("spruce_sign", with_material(&Material::Wood, ColorId::Brown), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("birch_sign", with_material(&Material::Wood, ColorId::Sand), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("acacia_sign", with_material(&Material::Wood, ColorId::Adobe), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("jungle_sign", with_material(&Material::Wood, ColorId::Obsidian), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("dark_oak_sign", with_material(&Material::Wood, ColorId::Brown), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("oak_door", with_material(&Material::Wood, ColorId::Wood), with_durability(3.0F), with_not_solid()),
   Block ("ladder", with_material(&Material::Miscellaneous), with_durability(0.4F), with_not_solid()),
   Block ("rail", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_durability(0.7F)),
   Block ("cobblestone_stairs", with_properties(cobblestone)),
   Block ("oak_wall_sign", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("oak_sign")),
   Block ("spruce_wall_sign", with_material(&Material::Wood, ColorId::Brown), with_does_not_block_movement(), with_durability(1.0F), with_loot("spruce_sign")),
   Block ("birch_wall_sign", with_material(&Material::Wood, ColorId::Sand), with_does_not_block_movement(), with_durability(1.0F), with_loot("birch_sign")),
   Block ("acacia_wall_sign", with_material(&Material::Wood, ColorId::Adobe), with_does_not_block_movement(), with_durability(1.0F), with_loot("acacia_sign")),
   Block ("jungle_wall_sign", with_material(&Material::Wood, ColorId::Obsidian), with_does_not_block_movement(), with_durability(1.0F), with_loot("jungle_sign")),
   Block ("dark_oak_wall_sign", with_material(&Material::Wood, ColorId::Brown), with_does_not_block_movement(), with_durability(1.0F), with_loot("dark_oak_sign")),
   Block ("lever", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("stone_pressure_plate", with_material(&Material::Rock), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("iron_door", with_material(&Material::Iron, ColorId::Iron), with_durability(5.0F), with_not_solid()),
   Block ("oak_pressure_plate", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("spruce_pressure_plate", with_material(&Material::Wood, ColorId::Brown), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("birch_pressure_plate", with_material(&Material::Wood, ColorId::Sand), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("jungle_pressure_plate", with_material(&Material::Wood, ColorId::Obsidian), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("acacia_pressure_plate", with_material(&Material::Wood, ColorId::Stone), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("dark_oak_pressure_plate", with_material(&Material::Wood, ColorId::Brown), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("redstone_ore", with_material(&Material::Rock), with_ticks_randomly(), with_light_value(9), with_durability(3.0F, 3.0F)),
   Block ("redstone_torch", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_zero_durability(), with_light_value(7)),
   Block ("redstone_wall_torch", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_zero_durability(), with_light_value(7), with_loot("redstone_torch")),
   Block ("stone_button", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("snow", with_material(&Material::Snow), with_ticks_randomly(), with_durability(0.1F)),
   Block ("ice", with_material(&Material::Ice), with_slipperiness(0.98F), with_ticks_randomly(), with_durability(0.5F), with_not_solid()),
   Block ("snow_block", with_material(&Material::SnowBlock), with_durability(0.2F)),
   Block ("cactus", with_material(&Material::Cactus), with_ticks_randomly(), with_durability(0.4F)),
   Block ("clay", with_material(&Material::Clay), with_durability(0.6F)),
   Block ("sugar_cane", with_material(&Material::Plants), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability()),
   Block ("jukebox", with_material(&Material::Wood, ColorId::Dirt), with_durability(2.0F, 6.0F)),
   Block ("oak_fence", with_material(&Material::Wood), with_durability(2.0F, 3.0F)),
   Block ("pumpkin", with_material(&Material::Gourd, ColorId::Adobe), with_durability(1.0F)),
   Block ("netherrack", with_material(&Material::Rock, ColorId::Netherrack), with_durability(0.4F)),
   Block ("soul_sand", with_material(&Material::Sand, ColorId::Brown), with_ticks_randomly(), with_durability(0.5F), with_speed_factor(0.4F)),
   Block ("glowstone", with_material(&Material::Glass, ColorId::Sand), with_durability(0.3F), with_light_value(15)),
   Block ("nether_portal", with_material(&Material::Portal), with_does_not_block_movement(), with_ticks_randomly(), with_durability(-1.0F), with_light_value(11), with_no_drop()),
   Block ("carved_pumpkin", with_material(&Material::Gourd, ColorId::Adobe), with_durability(1.0F)),
   Block ("jack_o_lantern", with_material(&Material::Gourd, ColorId::Adobe), with_durability(1.0F), with_light_value(15)),
   Block ("cake", with_material(&Material::Cake), with_durability(0.5F)),
   Block ("repeater", with_material(&Material::Miscellaneous), with_zero_durability()),
   Block ("white_stained_glass", with_material(&Material::Glass, DyeColor::from<ENU("white")>()), with_durability(0.3F), with_not_solid()),
   Block ("orange_stained_glass", with_material(&Material::Glass, DyeColor::from<ENU("orange")>()), with_durability(0.3F), with_not_solid()),
   Block ("magenta_stained_glass", with_material(&Material::Glass, DyeColor::from<ENU("magenta")>()), with_durability(0.3F), with_not_solid()),
   Block ("light_blue_stained_glass", with_material(&Material::Glass, DyeColor::from<ENU("light_blue")>()), with_durability(0.3F), with_not_solid()),
   Block ("yellow_stained_glass", with_material(&Material::Glass, DyeColor::from<ENU("yellow")>()), with_durability(0.3F), with_not_solid()),
   Block ("lime_stained_glass", with_material(&Material::Glass, DyeColor::from<ENU("lime")>()), with_durability(0.3F), with_not_solid()),
   Block ("pink_stained_glass", with_material(&Material::Glass, DyeColor::from<ENU("pink")>()), with_durability(0.3F), with_not_solid()),
   Block ("gray_stained_glass", with_material(&Material::Glass, DyeColor::from<ENU("gray")>()), with_durability(0.3F), with_not_solid()),
   Block ("light_gray_stained_glass", with_material(&Material::Glass, DyeColor::from<ENU("light_gray")>()), with_durability(0.3F), with_not_solid()),
   Block ("cyan_stained_glass", with_material(&Material::Glass, DyeColor::from<ENU("cyan")>()), with_durability(0.3F), with_not_solid()),
   Block ("purple_stained_glass", with_material(&Material::Glass, DyeColor::from<ENU("purple")>()), with_durability(0.3F), with_not_solid()),
   Block ("blue_stained_glass", with_material(&Material::Glass, DyeColor::from<ENU("blue")>()), with_durability(0.3F), with_not_solid()),
   Block ("brown_stained_glass", with_material(&Material::Glass, DyeColor::from<ENU("brown")>()), with_durability(0.3F), with_not_solid()),
   Block ("green_stained_glass", with_material(&Material::Glass, DyeColor::from<ENU("green")>()), with_durability(0.3F), with_not_solid()),
   Block ("red_stained_glass", with_material(&Material::Glass, DyeColor::from<ENU("red")>()), with_durability(0.3F), with_not_solid()),
   Block ("black_stained_glass", with_material(&Material::Glass, DyeColor::from<ENU("black")>()), with_durability(0.3F), with_not_solid()),
   Block ("oak_trapdoor", with_material(&Material::Wood, ColorId::Wood), with_durability(3.0F), with_not_solid()),
   Block ("spruce_trapdoor", with_material(&Material::Wood, ColorId::Obsidian), with_durability(3.0F), with_not_solid()),
   Block ("birch_trapdoor", with_material(&Material::Wood, ColorId::Sand), with_durability(3.0F), with_not_solid()),
   Block ("jungle_trapdoor", with_material(&Material::Wood, ColorId::Dirt), with_durability(3.0F), with_not_solid()),
   Block ("acacia_trapdoor", with_material(&Material::Wood, ColorId::Adobe), with_durability(3.0F), with_not_solid()),
   Block ("dark_oak_trapdoor", with_material(&Material::Wood, ColorId::Brown), with_durability(3.0F), with_not_solid()),
   Block ("stone_bricks", with_material(&Material::Rock), with_durability(1.5F, 6.0F)),
   Block ("mossy_stone_bricks", with_material(&Material::Rock), with_durability(1.5F, 6.0F)),
   Block ("cracked_stone_bricks", with_material(&Material::Rock), with_durability(1.5F, 6.0F)),
   Block ("chiseled_stone_bricks", with_material(&Material::Rock), with_durability(1.5F, 6.0F)),
   Block ("infested_stone", with_material(&Material::Clay), with_durability(0.0F, 0.75F)),
   Block ("infested_cobblestone", with_material(&Material::Clay), with_durability(0.0F, 0.75F)),
   Block ("infested_stone_bricks", with_material(&Material::Clay), with_durability(0.0F, 0.75F)),
   Block ("infested_mossy_stone_bricks", with_material(&Material::Clay), with_durability(0.0F, 0.75F)),
   Block ("infested_cracked_stone_bricks", with_material(&Material::Clay), with_durability(0.0F, 0.75F)),
   Block ("infested_chiseled_stone_bricks", with_material(&Material::Clay), with_durability(0.0F, 0.75F)),
   Block ("brown_mushroom_block", with_material(&Material::Wood, ColorId::Dirt), with_durability(0.2F)),
   Block ("red_mushroom_block", with_material(&Material::Wood, ColorId::Red), with_durability(0.2F)),
   Block ("mushroom_stem", with_material(&Material::Wood, ColorId::Wool), with_durability(0.2F)),
   Block ("iron_bars", with_material(&Material::Iron, ColorId::Air), with_durability(5.0F, 6.0F), with_not_solid()),
   Block ("glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("melon", with_material(&Material::Gourd, ColorId::Lime), with_durability(1.0F)),
   Block ("attached_pumpkin_stem", with_material(&Material::Plants), with_does_not_block_movement(), with_zero_durability()),
   Block ("attached_melon_stem", with_material(&Material::Plants), with_does_not_block_movement(), with_zero_durability()),
   Block ("pumpkin_stem", with_material(&Material::Plants), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability()),
   Block ("melon_stem", with_material(&Material::Plants), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability()),
   Block ("vine", with_material(&Material::TallPlants), with_does_not_block_movement(), with_ticks_randomly(), with_durability(0.2F)),
   Block ("oak_fence_gate", with_material(&Material::Wood), with_durability(2.0F, 3.0F)),
   Block ("brick_stairs", with_properties(bricks)),
   Block ("stone_brick_stairs", with_properties(stone_bricks)),
   Block ("mycelium", with_material(&Material::Organic, ColorId::Purple), with_ticks_randomly(), with_durability(0.6F)),
   Block ("lily_pad", with_material(&Material::Plants), with_zero_durability(), with_not_solid()),
   Block ("nether_bricks", with_material(&Material::Rock, ColorId::Netherrack), with_durability(2.0F, 6.0F)),
   Block ("nether_brick_fence", with_material(&Material::Rock, ColorId::Netherrack), with_durability(2.0F, 6.0F)),
   Block ("nether_brick_stairs", with_properties(nether_bricks)),
   Block ("nether_wart", with_material(&Material::Plants, ColorId::Red), with_does_not_block_movement(), with_ticks_randomly()),
   Block ("enchanting_table", with_material(&Material::Rock, ColorId::Red), with_durability(5.0F, 1200.0F)),
   Block ("brewing_stand", with_material(&Material::Iron), with_durability(0.5F), with_light_value(1), with_not_solid()),
   Block ("cauldron", with_material(&Material::Iron, ColorId::Stone), with_durability(2.0F), with_not_solid()),
   Block ("end_portal", with_material(&Material::Portal, ColorId::Black), with_does_not_block_movement(), with_light_value(15), with_durability(-1.0F, 3600000.0F), with_no_drop()),
   Block ("end_portal_frame", with_material(&Material::Rock, ColorId::Green), with_light_value(1), with_durability(-1.0F, 3600000.0F), with_no_drop()),
   Block ("end_stone", with_material(&Material::Rock, ColorId::Sand), with_durability(3.0F, 9.0F)),
   Block ("dragon_egg", with_material(&Material::DragonEgg, ColorId::Black), with_durability(3.0F, 9.0F), with_light_value(1), with_not_solid()),
   Block ("redstone_lamp", with_material(&Material::RedstoneLight), with_light_value(15), with_durability(0.3F)),
   Block ("cocoa", with_material(&Material::Plants), with_ticks_randomly(), with_durability(0.2F, 3.0F), with_not_solid()),
   Block ("sandstone_stairs", with_properties(sandstone)),
   Block ("emerald_ore", with_material(&Material::Rock), with_durability(3.0F, 3.0F)),
   Block ("ender_chest", with_material(&Material::Rock), with_durability(22.5F, 600.0F), with_light_value(7)),
   Block ("tripwire_hook", with_material(&Material::Miscellaneous), with_does_not_block_movement()),
   Block ("tripwire", with_material(&Material::Miscellaneous), with_does_not_block_movement()),
   Block ("emerald_block", with_material(&Material::Iron, ColorId::Emerald), with_durability(5.0F, 6.0F)),
   Block ("spruce_stairs", with_properties(spruce_planks)),
   Block ("birch_stairs", with_properties(birch_planks)),
   Block ("jungle_stairs", with_properties(jungle_planks)),
   Block ("command_block", with_material(&Material::Iron, ColorId::Brown), with_durability(-1.0F, 3600000.0F), with_no_drop()),
   Block ("beacon", with_material(&Material::Glass, ColorId::Diamond), with_durability(3.0F), with_light_value(15), with_not_solid()),
   Block ("cobblestone_wall", with_properties(cobblestone)),
   Block ("mossy_cobblestone_wall", with_properties(cobblestone)),
   Block ("flower_pot", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_oak_sapling", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_spruce_sapling", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_birch_sapling", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_jungle_sapling", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_acacia_sapling", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_dark_oak_sapling", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_fern", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_dandelion", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_poppy", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_blue_orchid", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_allium", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_azure_bluet", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_red_tulip", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_orange_tulip", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_white_tulip", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_pink_tulip", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_oxeye_daisy", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_cornflower", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_lily_of_the_valley", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_wither_rose", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_red_mushroom", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_brown_mushroom", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_dead_bush", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("potted_cactus", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("carrots", with_material(&Material::Plants), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability()),
   Block ("potatoes", with_material(&Material::Plants), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability()),
   Block ("oak_button", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("spruce_button", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("birch_button", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("jungle_button", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("acacia_button", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("dark_oak_button", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("skeleton_skull", with_material(&Material::Miscellaneous), with_durability(1.0F)),
   Block ("skeleton_wall_skull", with_material(&Material::Miscellaneous), with_durability(1.0F), with_loot("skeleton_skull")),
   Block ("wither_skeleton_skull", with_material(&Material::Miscellaneous), with_durability(1.0F)),
   Block ("wither_skeleton_wall_skull", with_material(&Material::Miscellaneous), with_durability(1.0F), with_loot("wither_skeleton_skull")),
   Block ("zombie_head", with_material(&Material::Miscellaneous), with_durability(1.0F)),
   Block ("zombie_wall_head", with_material(&Material::Miscellaneous), with_durability(1.0F), with_loot("zombie_head")),
   Block ("player_head", with_material(&Material::Miscellaneous), with_durability(1.0F)),
   Block ("player_wall_head", with_material(&Material::Miscellaneous), with_durability(1.0F), with_loot("player_head")),
   Block ("creeper_head", with_material(&Material::Miscellaneous), with_durability(1.0F)),
   Block ("creeper_wall_head", with_material(&Material::Miscellaneous), with_durability(1.0F), with_loot("creeper_head")),
   Block ("dragon_head", with_material(&Material::Miscellaneous), with_durability(1.0F)),
   Block ("dragon_wall_head", with_material(&Material::Miscellaneous), with_durability(1.0F), with_loot("dragon_head")),
   Block ("anvil", with_material(&Material::Anvil, ColorId::Iron), with_durability(5.0F, 1200.0F)),
   Block ("chipped_anvil", with_material(&Material::Anvil, ColorId::Iron), with_durability(5.0F, 1200.0F)),
   Block ("damaged_anvil", with_material(&Material::Anvil, ColorId::Iron), with_durability(5.0F, 1200.0F)),
   Block ("trapped_chest", with_material(&Material::Wood), with_durability(2.5F)),
   Block ("light_weighted_pressure_plate", with_material(&Material::Iron, ColorId::Gold), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("heavy_weighted_pressure_plate", with_material(&Material::Iron), with_does_not_block_movement(), with_durability(0.5F)),
   Block ("comparator", with_material(&Material::Miscellaneous), with_zero_durability()),
   Block ("daylight_detector", with_material(&Material::Wood), with_durability(0.2F)),
   Block ("redstone_block", with_material(&Material::Iron, ColorId::Tnt), with_durability(5.0F, 6.0F)),
   Block ("nether_quartz_ore", with_material(&Material::Rock, ColorId::Netherrack), with_durability(3.0F, 3.0F)),
   Block ("hopper", with_material(&Material::Iron, ColorId::Stone), with_durability(3.0F, 4.8F), with_not_solid()),
   Block ("quartz_block", with_material(&Material::Rock, ColorId::Quartz), with_durability(0.8F)),
   Block ("chiseled_quartz_block", with_material(&Material::Rock, ColorId::Quartz), with_durability(0.8F)),
   Block ("quartz_pillar", with_material(&Material::Rock, ColorId::Quartz), with_durability(0.8F)),
   Block ("quartz_stairs", with_properties(quartz_block)),
   Block ("activator_rail", with_material(&Material::Miscellaneous), with_does_not_block_movement(), with_durability(0.7F)),
   Block ("dropper", with_material(&Material::Rock), with_durability(3.5F)),
   Block ("white_terracotta", with_material(&Material::Rock, ColorId::WhiteTerracotta), with_durability(1.25F, 4.2F)),
   Block ("orange_terracotta", with_material(&Material::Rock, ColorId::OrangeTerracotta), with_durability(1.25F, 4.2F)),
   Block ("magenta_terracotta", with_material(&Material::Rock, ColorId::MagentaTerracotta), with_durability(1.25F, 4.2F)),
   Block ("light_blue_terracotta", with_material(&Material::Rock, ColorId::LightBlueTerracotta), with_durability(1.25F, 4.2F)),
   Block ("yellow_terracotta", with_material(&Material::Rock, ColorId::YellowTerracotta), with_durability(1.25F, 4.2F)),
   Block ("lime_terracotta", with_material(&Material::Rock, ColorId::LimeTerracotta), with_durability(1.25F, 4.2F)),
   Block ("pink_terracotta", with_material(&Material::Rock, ColorId::PinkTerracotta), with_durability(1.25F, 4.2F)),
   Block ("gray_terracotta", with_material(&Material::Rock, ColorId::GrayTerracotta), with_durability(1.25F, 4.2F)),
   Block ("light_gray_terracotta", with_material(&Material::Rock, ColorId::LightGrayTerracotta), with_durability(1.25F, 4.2F)),
   Block ("cyan_terracotta", with_material(&Material::Rock, ColorId::CyanTerracotta), with_durability(1.25F, 4.2F)),
   Block ("purple_terracotta", with_material(&Material::Rock, ColorId::PurpleTerracotta), with_durability(1.25F, 4.2F)),
   Block ("blue_terracotta", with_material(&Material::Rock, ColorId::BlueTerracotta), with_durability(1.25F, 4.2F)),
   Block ("brown_terracotta", with_material(&Material::Rock, ColorId::BrownTerracotta), with_durability(1.25F, 4.2F)),
   Block ("green_terracotta", with_material(&Material::Rock, ColorId::GreenTerracotta), with_durability(1.25F, 4.2F)),
   Block ("red_terracotta", with_material(&Material::Rock, ColorId::RedTerracotta), with_durability(1.25F, 4.2F)),
   Block ("black_terracotta", with_material(&Material::Rock, ColorId::BlackTerracotta), with_durability(1.25F, 4.2F)),
   Block ("white_stained_glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("orange_stained_glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("magenta_stained_glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("light_blue_stained_glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("yellow_stained_glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("lime_stained_glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("pink_stained_glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("gray_stained_glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("light_gray_stained_glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("cyan_stained_glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("purple_stained_glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("blue_stained_glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("brown_stained_glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("green_stained_glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("red_stained_glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("black_stained_glass_pane", with_material(&Material::Glass), with_durability(0.3F), with_not_solid()),
   Block ("acacia_stairs", with_properties(acacia_planks)),
   Block ("dark_oak_stairs", with_properties(dark_oak_planks)),
   Block ("slime_block", with_material(&Material::Clay, ColorId::Grass), with_slipperiness(0.8F), with_not_solid()),
   Block ("barrier", with_material(&Material::Barrier), with_durability(-1.0F, 3600000.8F), with_no_drop(), with_not_solid()),
   Block ("iron_trapdoor", with_material(&Material::Iron), with_durability(5.0F), with_not_solid()),
   Block ("prismarine", with_material(&Material::Rock, ColorId::Cyan), with_durability(1.5F, 6.0F)),
   Block ("prismarine_bricks", with_material(&Material::Rock, ColorId::Diamond), with_durability(1.5F, 6.0F)),
   Block ("dark_prismarine", with_material(&Material::Rock, ColorId::Diamond), with_durability(1.5F, 6.0F)),
   Block ("prismarine_stairs", with_properties(prismarine)),
   Block ("prismarine_brick_stairs", with_properties(prismarine_bricks)),
   Block ("dark_prismarine_stairs", with_properties(dark_prismarine)),
   Block ("prismarine_slab", with_material(&Material::Rock, ColorId::Cyan), with_durability(1.5F, 6.0F)),
   Block ("prismarine_brick_slab", with_material(&Material::Rock, ColorId::Diamond), with_durability(1.5F, 6.0F)),
   Block ("dark_prismarine_slab", with_material(&Material::Rock, ColorId::Diamond), with_durability(1.5F, 6.0F)),
   Block ("sea_lantern", with_material(&Material::Glass, ColorId::Quartz), with_durability(0.3F), with_light_value(15)),
   Block ("hay_block", with_material(&Material::Organic, ColorId::Yellow), with_durability(0.5F)),
   Block ("white_carpet", with_material(&Material::Carpet, ColorId::Snow), with_durability(0.1F)),
   Block ("orange_carpet", with_material(&Material::Carpet, ColorId::Adobe), with_durability(0.1F)),
   Block ("magenta_carpet", with_material(&Material::Carpet, ColorId::Magenta), with_durability(0.1F)),
   Block ("light_blue_carpet", with_material(&Material::Carpet, ColorId::LightBlue), with_durability(0.1F)),
   Block ("yellow_carpet", with_material(&Material::Carpet, ColorId::Yellow), with_durability(0.1F)),
   Block ("lime_carpet", with_material(&Material::Carpet, ColorId::Lime), with_durability(0.1F)),
   Block ("pink_carpet", with_material(&Material::Carpet, ColorId::Pink), with_durability(0.1F)),
   Block ("gray_carpet", with_material(&Material::Carpet, ColorId::Gray), with_durability(0.1F)),
   Block ("light_gray_carpet", with_material(&Material::Carpet, ColorId::LightGray), with_durability(0.1F)),
   Block ("cyan_carpet", with_material(&Material::Carpet, ColorId::Cyan), with_durability(0.1F)),
   Block ("purple_carpet", with_material(&Material::Carpet, ColorId::Purple), with_durability(0.1F)),
   Block ("blue_carpet", with_material(&Material::Carpet, ColorId::Blue), with_durability(0.1F)),
   Block ("brown_carpet", with_material(&Material::Carpet, ColorId::Brown), with_durability(0.1F)),
   Block ("green_carpet", with_material(&Material::Carpet, ColorId::Green), with_durability(0.1F)),
   Block ("red_carpet", with_material(&Material::Carpet, ColorId::Red), with_durability(0.1F)),
   Block ("black_carpet", with_material(&Material::Carpet, ColorId::Black), with_durability(0.1F)),
   Block ("terracotta", with_material(&Material::Rock, ColorId::Adobe), with_durability(1.25F, 4.2F)),
   Block ("coal_block", with_material(&Material::Rock, ColorId::Black), with_durability(5.0F, 6.0F)),
   Block ("packed_ice", with_material(&Material::PackedIce), with_slipperiness(0.98F), with_durability(0.5F)),
   Block ("sunflower", with_material(&Material::TallPlants), with_does_not_block_movement(), with_zero_durability()),
   Block ("lilac", with_material(&Material::TallPlants), with_does_not_block_movement(), with_zero_durability()),
   Block ("rose_bush", with_material(&Material::TallPlants), with_does_not_block_movement(), with_zero_durability()),
   Block ("peony", with_material(&Material::TallPlants), with_does_not_block_movement(), with_zero_durability()),
   Block ("tall_grass", with_material(&Material::TallPlants), with_does_not_block_movement(), with_zero_durability()),
   Block ("large_fern", with_material(&Material::TallPlants), with_does_not_block_movement(), with_zero_durability()),
   Block ("white_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("orange_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("magenta_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("light_blue_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("yellow_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("lime_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("pink_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("gray_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("light_gray_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("cyan_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("purple_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("blue_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("brown_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("green_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("red_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("black_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("white_wall_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("white_banner")),
   Block ("orange_wall_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("orange_banner")),
   Block ("magenta_wall_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("magenta_banner")),
   Block ("light_blue_wall_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("lightblue_banner")),
   Block ("yellow_wall_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("yellow_banner")),
   Block ("lime_wall_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("lime_banner")),
   Block ("pink_wall_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("pink_banner")),
   Block ("gray_wall_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("gray_banner")),
   Block ("light_gray_wall_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("lightgray_banner")),
   Block ("cyan_wall_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("cyan_banner")),
   Block ("purple_wall_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("purple_banner")),
   Block ("blue_wall_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("blue_banner")),
   Block ("brown_wall_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("brown_banner")),
   Block ("green_wall_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("green_banner")),
   Block ("red_wall_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("red_banner")),
   Block ("black_wall_banner", with_material(&Material::Wood), with_does_not_block_movement(), with_durability(1.0F), with_loot("black_banner")),
   Block ("red_sandstone", with_material(&Material::Rock, ColorId::Adobe), with_durability(0.8F)),
   Block ("chiseled_red_sandstone", with_material(&Material::Rock, ColorId::Adobe), with_durability(0.8F)),
   Block ("cut_red_sandstone", with_material(&Material::Rock, ColorId::Adobe), with_durability(0.8F)),
   Block ("red_sandstone_stairs", with_properties(red_sandstone)),
   Block ("oak_slab", with_material(&Material::Wood, ColorId::Wood), with_durability(2.0F, 3.0F)),
   Block ("spruce_slab", with_material(&Material::Wood, ColorId::Obsidian), with_durability(2.0F, 3.0F)),
   Block ("birch_slab", with_material(&Material::Wood, ColorId::Sand), with_durability(2.0F, 3.0F)),
   Block ("jungle_slab", with_material(&Material::Wood, ColorId::Dirt), with_durability(2.0F, 3.0F)),
   Block ("acacia_slab", with_material(&Material::Wood, ColorId::Adobe), with_durability(2.0F, 3.0F)),
   Block ("dark_oak_slab", with_material(&Material::Wood, ColorId::Brown), with_durability(2.0F, 3.0F)),
   Block ("stone_slab", with_material(&Material::Rock, ColorId::Stone), with_durability(2.0F, 6.0F)),
   Block ("smooth_stone_slab", with_material(&Material::Rock, ColorId::Stone), with_durability(2.0F, 6.0F)),
   Block ("sandstone_slab", with_material(&Material::Rock, ColorId::Sand), with_durability(2.0F, 6.0F)),
   Block ("cut_sandstone_slab", with_material(&Material::Rock, ColorId::Sand), with_durability(2.0F, 6.0F)),
   Block ("petrified_oak_slab", with_material(&Material::Rock, ColorId::Wood), with_durability(2.0F, 6.0F)),
   Block ("cobblestone_slab", with_material(&Material::Rock, ColorId::Stone), with_durability(2.0F, 6.0F)),
   Block ("brick_slab", with_material(&Material::Rock, ColorId::Red), with_durability(2.0F, 6.0F)),
   Block ("stone_brick_slab", with_material(&Material::Rock, ColorId::Stone), with_durability(2.0F, 6.0F)),
   Block ("nether_brick_slab", with_material(&Material::Rock, ColorId::Netherrack), with_durability(2.0F, 6.0F)),
   Block ("quartz_slab", with_material(&Material::Rock, ColorId::Quartz), with_durability(2.0F, 6.0F)),
   Block ("red_sandstone_slab", with_material(&Material::Rock, ColorId::Adobe), with_durability(2.0F, 6.0F)),
   Block ("cut_red_sandstone_slab", with_material(&Material::Rock, ColorId::Adobe), with_durability(2.0F, 6.0F)),
   Block ("purpur_slab", with_material(&Material::Rock, ColorId::Magenta), with_durability(2.0F, 6.0F)),
   Block ("smooth_stone", with_material(&Material::Rock, ColorId::Stone), with_durability(2.0F, 6.0F)),
   Block ("smooth_sandstone", with_material(&Material::Rock, ColorId::Sand), with_durability(2.0F, 6.0F)),
   Block ("smooth_quartz", with_material(&Material::Rock, ColorId::Quartz), with_durability(2.0F, 6.0F)),
   Block ("smooth_red_sandstone", with_material(&Material::Rock, ColorId::Adobe), with_durability(2.0F, 6.0F)),
   Block ("spruce_fence_gate", with_material(&Material::Wood, ColorId::Brown), with_durability(2.0F, 3.0F)),
   Block ("birch_fence_gate", with_material(&Material::Wood, ColorId::Sand), with_durability(2.0F, 3.0F)),
   Block ("jungle_fence_gate", with_material(&Material::Wood, ColorId::Obsidian), with_durability(2.0F, 3.0F)),
   Block ("acacia_fence_gate", with_material(&Material::Wood, ColorId::Stone), with_durability(2.0F, 3.0F)),
   Block ("dark_oak_fence_gate", with_material(&Material::Wood, ColorId::Brown), with_durability(2.0F, 3.0F)),
   Block ("spruce_fence", with_material(&Material::Wood, ColorId::Brown), with_durability(2.0F, 3.0F)),
   Block ("birch_fence", with_material(&Material::Wood, ColorId::Sand), with_durability(2.0F, 3.0F)),
   Block ("jungle_fence", with_material(&Material::Wood, ColorId::Obsidian), with_durability(2.0F, 3.0F)),
   Block ("acacia_fence", with_material(&Material::Wood, ColorId::Stone), with_durability(2.0F, 3.0F)),
   Block ("dark_oak_fence", with_material(&Material::Wood, ColorId::Brown), with_durability(2.0F, 3.0F)),
   Block ("spruce_door", with_material(&Material::Wood, ColorId::Brown), with_durability(3.0F), with_not_solid()),
   Block ("birch_door", with_material(&Material::Wood, ColorId::Sand), with_durability(3.0F), with_not_solid()),
   Block ("jungle_door", with_material(&Material::Wood, ColorId::Obsidian), with_durability(3.0F), with_not_solid()),
   Block ("acacia_door", with_material(&Material::Wood, ColorId::Stone), with_durability(3.0F), with_not_solid()),
   Block ("dark_oak_door", with_material(&Material::Wood, ColorId::Brown), with_durability(3.0F), with_not_solid()),
   Block ("end_rod", with_material(&Material::Miscellaneous), with_zero_durability(), with_light_value(14), with_not_solid()),
   Block ("chorus_plant", with_material(&Material::Plants, ColorId::Purple), with_durability(0.4F), with_not_solid()),
   Block ("chorus_flower", with_material(&Material::Plants, ColorId::Purple), with_ticks_randomly(), with_durability(0.4F), with_not_solid()),
   Block ("purpur_block", with_material(&Material::Rock, ColorId::Magenta), with_durability(1.5F, 6.0F)),
   Block ("purpur_pillar", with_material(&Material::Rock, ColorId::Magenta), with_durability(1.5F, 6.0F)),
   Block ("purpur_stairs", with_properties(purpur_block)),
   Block ("end_stone_bricks", with_material(&Material::Rock, ColorId::Sand), with_durability(3.0F, 9.0F)),
   Block ("beetroots", with_material(&Material::Plants), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability()),
   Block ("grass_path", with_material(&Material::Earth), with_durability(0.65F)),
   Block ("end_gateway", with_material(&Material::Portal, ColorId::Black), with_does_not_block_movement(), with_light_value(15), with_durability(-1.0F, 3600000.0F), with_no_drop()),
   Block ("repeating_command_block", with_material(&Material::Iron, ColorId::Purple), with_durability(-1.0F, 3600000.0F), with_no_drop()),
   Block ("chain_command_block", with_material(&Material::Iron, ColorId::Green), with_durability(-1.0F, 3600000.0F), with_no_drop()),
   Block ("frosted_ice", with_material(&Material::Ice), with_slipperiness(0.98F), with_ticks_randomly(), with_durability(0.5F), with_not_solid()),
   Block ("magma_block", with_material(&Material::Rock, ColorId::Netherrack), with_light_value(3), with_ticks_randomly(), with_durability(0.5F)),
   Block ("nether_wart_block", with_material(&Material::Organic, ColorId::Red), with_durability(1.0F)),
   Block ("red_nether_bricks", with_material(&Material::Rock, ColorId::Netherrack), with_durability(2.0F, 6.0F)),
   Block ("bone_block", with_material(&Material::Rock, ColorId::Sand), with_durability(2.0F)),
   Block ("structure_void", with_material(&Material::StructureVoid), with_does_not_block_movement(), with_no_drop()),
   Block ("observer", with_material(&Material::Rock), with_durability(3.0F)),
   Block ("shulker_box", with_material(&Material::Shulker), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("white_shulker_box", with_material(&Material::Shulker, ColorId::Snow), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("orange_shulker_box", with_material(&Material::Shulker, ColorId::Adobe), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("magenta_shulker_box", with_material(&Material::Shulker, ColorId::Magenta), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("light_blue_shulker_box", with_material(&Material::Shulker, ColorId::LightBlue), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("yellow_shulker_box", with_material(&Material::Shulker, ColorId::Yellow), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("lime_shulker_box", with_material(&Material::Shulker, ColorId::Lime), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("pink_shulker_box", with_material(&Material::Shulker, ColorId::Pink), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("gray_shulker_box", with_material(&Material::Shulker, ColorId::Gray), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("light_gray_shulker_box", with_material(&Material::Shulker, ColorId::LightGray), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("cyan_shulker_box", with_material(&Material::Shulker, ColorId::Cyan), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("purple_shulker_box", with_material(&Material::Shulker, ColorId::PurpleTerracotta), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("blue_shulker_box", with_material(&Material::Shulker, ColorId::Blue), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("brown_shulker_box", with_material(&Material::Shulker, ColorId::Brown), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("green_shulker_box", with_material(&Material::Shulker, ColorId::Green), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("red_shulker_box", with_material(&Material::Shulker, ColorId::Red), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("black_shulker_box", with_material(&Material::Shulker, ColorId::Black), with_durability(2.0F), with_variable_opacity(), with_not_solid()),
   Block ("white_glazed_terracotta", with_material(&Material::Rock, DyeColor::from<ENU("white")>()), with_durability(1.4F)),
   Block ("orange_glazed_terracotta", with_material(&Material::Rock, DyeColor::from<ENU("orange")>()), with_durability(1.4F)),
   Block ("magenta_glazed_terracotta", with_material(&Material::Rock, DyeColor::from<ENU("magenta")>()), with_durability(1.4F)),
   Block ("light_blue_glazed_terracotta", with_material(&Material::Rock, DyeColor::from<ENU("light_blue")>()), with_durability(1.4F)),
   Block ("yellow_glazed_terracotta", with_material(&Material::Rock, DyeColor::from<ENU("yellow")>()), with_durability(1.4F)),
   Block ("lime_glazed_terracotta", with_material(&Material::Rock, DyeColor::from<ENU("lime")>()), with_durability(1.4F)),
   Block ("pink_glazed_terracotta", with_material(&Material::Rock, DyeColor::from<ENU("pink")>()), with_durability(1.4F)),
   Block ("gray_glazed_terracotta", with_material(&Material::Rock, DyeColor::from<ENU("gray")>()), with_durability(1.4F)),
   Block ("light_gray_glazed_terracotta", with_material(&Material::Rock, DyeColor::from<ENU("light_gray")>()), with_durability(1.4F)),
   Block ("cyan_glazed_terracotta", with_material(&Material::Rock, DyeColor::from<ENU("cyan")>()), with_durability(1.4F)),
   Block ("purple_glazed_terracotta", with_material(&Material::Rock, DyeColor::from<ENU("purple")>()), with_durability(1.4F)),
   Block ("blue_glazed_terracotta", with_material(&Material::Rock, DyeColor::from<ENU("blue")>()), with_durability(1.4F)),
   Block ("brown_glazed_terracotta", with_material(&Material::Rock, DyeColor::from<ENU("brown")>()), with_durability(1.4F)),
   Block ("green_glazed_terracotta", with_material(&Material::Rock, DyeColor::from<ENU("green")>()), with_durability(1.4F)),
   Block ("red_glazed_terracotta", with_material(&Material::Rock, DyeColor::from<ENU("red")>()), with_durability(1.4F)),
   Block ("black_glazed_terracotta", with_material(&Material::Rock, DyeColor::from<ENU("black")>()), with_durability(1.4F)),
   Block ("white_concrete", with_material(&Material::Rock, DyeColor::from<ENU("white")>()), with_durability(1.8F)),
   Block ("orange_concrete", with_material(&Material::Rock, DyeColor::from<ENU("orange")>()), with_durability(1.8F)),
   Block ("magenta_concrete", with_material(&Material::Rock, DyeColor::from<ENU("magenta")>()), with_durability(1.8F)),
   Block ("light_blue_concrete", with_material(&Material::Rock, DyeColor::from<ENU("light_blue")>()), with_durability(1.8F)),
   Block ("yellow_concrete", with_material(&Material::Rock, DyeColor::from<ENU("yellow")>()), with_durability(1.8F)),
   Block ("lime_concrete", with_material(&Material::Rock, DyeColor::from<ENU("lime")>()), with_durability(1.8F)),
   Block ("pink_concrete", with_material(&Material::Rock, DyeColor::from<ENU("pink")>()), with_durability(1.8F)),
   Block ("gray_concrete", with_material(&Material::Rock, DyeColor::from<ENU("gray")>()), with_durability(1.8F)),
   Block ("light_gray_concrete", with_material(&Material::Rock, DyeColor::from<ENU("light_gray")>()), with_durability(1.8F)),
   Block ("cyan_concrete", with_material(&Material::Rock, DyeColor::from<ENU("cyan")>()), with_durability(1.8F)),
   Block ("purple_concrete", with_material(&Material::Rock, DyeColor::from<ENU("purple")>()), with_durability(1.8F)),
   Block ("blue_concrete", with_material(&Material::Rock, DyeColor::from<ENU("blue")>()), with_durability(1.8F)),
   Block ("brown_concrete", with_material(&Material::Rock, DyeColor::from<ENU("brown")>()), with_durability(1.8F)),
   Block ("green_concrete", with_material(&Material::Rock, DyeColor::from<ENU("green")>()), with_durability(1.8F)),
   Block ("red_concrete", with_material(&Material::Rock, DyeColor::from<ENU("red")>()), with_durability(1.8F)),
   Block ("black_concrete", with_material(&Material::Rock, DyeColor::from<ENU("black")>()), with_durability(1.8F)),
   Block ("white_concrete_powder", with_material(&Material::Sand, DyeColor::from<ENU("white")>()), with_durability(0.5F)),
   Block ("orange_concrete_powder", with_material(&Material::Sand, DyeColor::from<ENU("orange")>()), with_durability(0.5F)),
   Block ("magenta_concrete_powder", with_material(&Material::Sand, DyeColor::from<ENU("magenta")>()), with_durability(0.5F)),
   Block ("light_blue_concrete_powder", with_material(&Material::Sand, DyeColor::from<ENU("light_blue")>()), with_durability(0.5F)),
   Block ("yellow_concrete_powder", with_material(&Material::Sand, DyeColor::from<ENU("yellow")>()), with_durability(0.5F)),
   Block ("lime_concrete_powder", with_material(&Material::Sand, DyeColor::from<ENU("lime")>()), with_durability(0.5F)),
   Block ("pink_concrete_powder", with_material(&Material::Sand, DyeColor::from<ENU("pink")>()), with_durability(0.5F)),
   Block ("gray_concrete_powder", with_material(&Material::Sand, DyeColor::from<ENU("gray")>()), with_durability(0.5F)),
   Block ("light_gray_concrete_powder", with_material(&Material::Sand, DyeColor::from<ENU("light_gray")>()), with_durability(0.5F)),
   Block ("cyan_concrete_powder", with_material(&Material::Sand, DyeColor::from<ENU("cyan")>()), with_durability(0.5F)),
   Block ("purple_concrete_powder", with_material(&Material::Sand, DyeColor::from<ENU("purple")>()), with_durability(0.5F)),
   Block ("blue_concrete_powder", with_material(&Material::Sand, DyeColor::from<ENU("blue")>()), with_durability(0.5F)),
   Block ("brown_concrete_powder", with_material(&Material::Sand, DyeColor::from<ENU("brown")>()), with_durability(0.5F)),
   Block ("green_concrete_powder", with_material(&Material::Sand, DyeColor::from<ENU("green")>()), with_durability(0.5F)),
   Block ("red_concrete_powder", with_material(&Material::Sand, DyeColor::from<ENU("red")>()), with_durability(0.5F)),
   Block ("black_concrete_powder", with_material(&Material::Sand, DyeColor::from<ENU("black")>()), with_durability(0.5F)),
   Block ("kelp", with_material(&Material::OceanPlant), with_does_not_block_movement(), with_ticks_randomly(), with_zero_durability()),
   Block ("kelp_plant", with_material(&Material::OceanPlant), with_does_not_block_movement(), with_zero_durability()),
   Block ("dried_kelp_block", with_material(&Material::Organic, ColorId::Green), with_durability(0.5F, 2.5F)),
   Block ("turtle_egg", with_material(&Material::DragonEgg, ColorId::Sand), with_durability(0.5F), with_ticks_randomly(), with_not_solid()),
   Block ("dead_tube_coral_block", with_material(&Material::Rock, ColorId::Gray), with_durability(1.5F, 6.0F)),
   Block ("dead_brain_coral_block", with_material(&Material::Rock, ColorId::Gray), with_durability(1.5F, 6.0F)),
   Block ("dead_bubble_coral_block", with_material(&Material::Rock, ColorId::Gray), with_durability(1.5F, 6.0F)),
   Block ("dead_fire_coral_block", with_material(&Material::Rock, ColorId::Gray), with_durability(1.5F, 6.0F)),
   Block ("dead_horn_coral_block", with_material(&Material::Rock, ColorId::Gray), with_durability(1.5F, 6.0F)),
   Block ("tube_coral_block", with_material(&Material::Rock, ColorId::Blue), with_durability(1.5F, 6.0F)),
   Block ("brain_coral_block", with_material(&Material::Rock, ColorId::Pink), with_durability(1.5F, 6.0F)),
   Block ("bubble_coral_block", with_material(&Material::Rock, ColorId::Purple), with_durability(1.5F, 6.0F)),
   Block ("fire_coral_block", with_material(&Material::Rock, ColorId::Red), with_durability(1.5F, 6.0F)),
   Block ("horn_coral_block", with_material(&Material::Rock, ColorId::Yellow), with_durability(1.5F, 6.0F)),
   Block ("dead_tube_coral", with_material(&Material::Rock, ColorId::Gray), with_does_not_block_movement(), with_zero_durability()),
   Block ("dead_brain_coral", with_material(&Material::Rock, ColorId::Gray), with_does_not_block_movement(), with_zero_durability()),
   Block ("dead_bubble_coral", with_material(&Material::Rock, ColorId::Gray), with_does_not_block_movement(), with_zero_durability()),
   Block ("dead_fire_coral", with_material(&Material::Rock, ColorId::Gray), with_does_not_block_movement(), with_zero_durability()),
   Block ("dead_horn_coral", with_material(&Material::Rock, ColorId::Gray), with_does_not_block_movement(), with_zero_durability()),
   Block ("tube_coral", with_material(&Material::OceanPlant, ColorId::Blue), with_does_not_block_movement(), with_zero_durability()),
   Block ("brain_coral", with_material(&Material::OceanPlant, ColorId::Pink), with_does_not_block_movement(), with_zero_durability()),
   Block ("bubble_coral", with_material(&Material::OceanPlant, ColorId::Purple), with_does_not_block_movement(), with_zero_durability()),
   Block ("fire_coral", with_material(&Material::OceanPlant, ColorId::Red), with_does_not_block_movement(), with_zero_durability()),
   Block ("horn_coral", with_material(&Material::OceanPlant, ColorId::Yellow), with_does_not_block_movement(), with_zero_durability()),
   Block ("dead_tube_coral_fan", with_material(&Material::Rock, ColorId::Gray), with_does_not_block_movement(), with_zero_durability()),
   Block ("dead_brain_coral_fan", with_material(&Material::Rock, ColorId::Gray), with_does_not_block_movement(), with_zero_durability()),
   Block ("dead_bubble_coral_fan", with_material(&Material::Rock, ColorId::Gray), with_does_not_block_movement(), with_zero_durability()),
   Block ("dead_fire_coral_fan", with_material(&Material::Rock, ColorId::Gray), with_does_not_block_movement(), with_zero_durability()),
   Block ("dead_horn_coral_fan", with_material(&Material::Rock, ColorId::Gray), with_does_not_block_movement(), with_zero_durability()),
   Block ("tube_coral_fan", with_material(&Material::OceanPlant, ColorId::Blue), with_does_not_block_movement(), with_zero_durability()),
   Block ("brain_coral_fan", with_material(&Material::OceanPlant, ColorId::Pink), with_does_not_block_movement(), with_zero_durability()),
   Block ("bubble_coral_fan", with_material(&Material::OceanPlant, ColorId::Purple), with_does_not_block_movement(), with_zero_durability()),
   Block ("fire_coral_fan", with_material(&Material::OceanPlant, ColorId::Red), with_does_not_block_movement(), with_zero_durability()),
   Block ("horn_coral_fan", with_material(&Material::OceanPlant, ColorId::Yellow), with_does_not_block_movement(), with_zero_durability()),
   Block ("dead_tube_coral_wall_fan", with_material(&Material::Rock, ColorId::Gray), with_does_not_block_movement(), with_zero_durability(), with_loot("dead_tube_coral_fan")),
   Block ("dead_brain_coral_wall_fan", with_material(&Material::Rock, ColorId::Gray), with_does_not_block_movement(), with_zero_durability(), with_loot("dead_brain_coral_fan")),
   Block ("dead_bubble_coral_wall_fan", with_material(&Material::Rock, ColorId::Gray), with_does_not_block_movement(), with_zero_durability(), with_loot("dead_bubble_coral_fan")),
   Block ("dead_fire_coral_wall_fan", with_material(&Material::Rock, ColorId::Gray), with_does_not_block_movement(), with_zero_durability(), with_loot("dead_fire_coral_fan")),
   Block ("dead_horn_coral_wall_fan", with_material(&Material::Rock, ColorId::Gray), with_does_not_block_movement(), with_zero_durability(), with_loot("dead_horn_coral_fan")),
   Block ("tube_coral_wall_fan", with_material(&Material::OceanPlant, ColorId::Blue), with_does_not_block_movement(), with_zero_durability(), with_loot("tube_coral_fan")),
   Block ("brain_coral_wall_fan", with_material(&Material::OceanPlant, ColorId::Pink), with_does_not_block_movement(), with_zero_durability(), with_loot("brain_coral_fan")),
   Block ("bubble_coral_wall_fan", with_material(&Material::OceanPlant, ColorId::Purple), with_does_not_block_movement(), with_zero_durability(), with_loot("bubble_coral_fan")),
   Block ("fire_coral_wall_fan", with_material(&Material::OceanPlant, ColorId::Red), with_does_not_block_movement(), with_zero_durability(), with_loot("fire_coral_fan")),
   Block ("horn_coral_wall_fan", with_material(&Material::OceanPlant, ColorId::Yellow), with_does_not_block_movement(), with_zero_durability(), with_loot("horn_coral_fan")),
   Block ("sea_pickle", with_material(&Material::OceanPlant, ColorId::Green), with_light_value(3), with_not_solid()),
   Block ("blue_ice", with_material(&Material::PackedIce), with_durability(2.8F), with_slipperiness(0.989F)),
   Block ("conduit", with_material(&Material::Glass, ColorId::Diamond), with_durability(3.0F), with_light_value(15), with_not_solid()),
   Block ("bamboo_sapling", with_material(&Material::BambooSapling), with_ticks_randomly(), with_zero_durability(), with_does_not_block_movement(), with_durability(1.0F)),
   Block ("bamboo", with_material(&Material::Bamboo, ColorId::Foliage), with_ticks_randomly(), with_zero_durability(), with_durability(1.0F), with_not_solid()),
   Block ("potted_bamboo", with_material(&Material::Miscellaneous), with_zero_durability(), with_not_solid()),
   Block ("void_air", with_material(&Material::Air), with_does_not_block_movement(), with_no_drop()),
   Block ("cave_air", with_material(&Material::Air), with_does_not_block_movement(), with_no_drop()),
   Block ("bubble_column", with_material(&Material::BubbleColumn), with_does_not_block_movement(), with_no_drop()),
   Block ("polished_granite_stairs", with_properties(polished_granite)),
   Block ("smooth_red_sandstone_stairs", with_properties(smooth_red_sandstone)),
   Block ("mossy_stone_brick_stairs", with_properties(mossy_stone_bricks)),
   Block ("polished_diorite_stairs", with_properties(polished_diorite)),
   Block ("mossy_cobblestone_stairs", with_properties(mossy_cobblestone)),
   Block ("end_stone_brick_stairs", with_properties(end_stone_bricks)),
   Block ("stone_stairs", with_properties(stone)),
   Block ("smooth_sandstone_stairs", with_properties(smooth_sandstone)),
   Block ("smooth_quartz_stairs", with_properties(smooth_quartz)),
   Block ("granite_stairs", with_properties(granite)),
   Block ("andesite_stairs", with_properties(andesite)),
   Block ("red_nether_brick_stairs", with_properties(red_nether_bricks)),
   Block ("polished_andesite_stairs", with_properties(polished_andesite)),
   Block ("diorite_stairs", with_properties(diorite)),
   Block ("polished_granite_slab", with_properties(polished_granite)),
   Block ("smooth_red_sandstone_slab", with_properties(smooth_red_sandstone)),
   Block ("mossy_stone_brick_slab", with_properties(mossy_stone_bricks)),
   Block ("polished_diorite_slab", with_properties(polished_diorite)),
   Block ("mossy_cobblestone_slab", with_properties(mossy_cobblestone)),
   Block ("end_stone_brick_slab", with_properties(end_stone_bricks)),
   Block ("smooth_sandstone_slab", with_properties(smooth_sandstone)),
   Block ("smooth_quartz_slab", with_properties(smooth_quartz)),
   Block ("granite_slab", with_properties(granite)),
   Block ("andesite_slab", with_properties(andesite)),
   Block ("red_nether_brick_slab", with_properties(red_nether_bricks)),
   Block ("polished_andesite_slab", with_properties(polished_andesite)),
   Block ("diorite_slab", with_properties(diorite)),
   Block ("brick_wall", with_properties(bricks)),
   Block ("prismarine_wall", with_properties(prismarine)),
   Block ("red_sandstone_wall", with_properties(red_sandstone)),
   Block ("mossy_stone_brick_wall", with_properties(mossy_stone_bricks)),
   Block ("granite_wall", with_properties(granite)),
   Block ("stone_brick_wall", with_properties(stone_bricks)),
   Block ("nether_brick_wall", with_properties(nether_bricks)),
   Block ("andesite_wall", with_properties(andesite)),
   Block ("red_nether_brick_wall", with_properties(red_nether_bricks)),
   Block ("sandstone_wall", with_properties(sandstone)),
   Block ("end_stone_brick_wall", with_properties(end_stone_bricks)),
   Block ("diorite_wall", with_properties(diorite)),
   Block ("scaffolding", with_material(&Material::Miscellaneous, ColorId::Sand), with_does_not_block_movement(), with_variable_opacity()),
   Block ("loom", with_material(&Material::Wood), with_durability(2.5F)),
   Block ("barrel", with_material(&Material::Wood), with_durability(2.5F)),
   Block ("smoker", with_material(&Material::Rock), with_durability(3.5F), with_light_value(13)),
   Block ("blast_furnace", with_material(&Material::Rock), with_durability(3.5F), with_light_value(13)),
   Block ("cartography_table", with_material(&Material::Wood), with_durability(2.5F)),
   Block ("fletching_table", with_material(&Material::Wood), with_durability(2.5F)),
   Block ("grindstone", with_material(&Material::Anvil, ColorId::Iron), with_durability(2.0F, 6.0F)),
   Block ("lectern", with_material(&Material::Wood), with_durability(2.5F)),
   Block ("smithing_table", with_material(&Material::Wood), with_durability(2.5F)),
   Block ("stonecutter", with_material(&Material::Rock), with_durability(3.5F)),
   Block ("bell", with_material(&Material::Iron, ColorId::Gold), with_durability(5.0F)),
   Block ("lantern", with_material(&Material::Iron), with_durability(3.5F), with_light_value(15), with_not_solid()),
   Block ("campfire", with_material(&Material::Wood, ColorId::Obsidian), with_durability(2.0F), with_light_value(15), with_ticks_randomly(), with_not_solid()),
   Block ("sweet_berry_bush", with_material(&Material::Plants), with_ticks_randomly(), with_does_not_block_movement()),
   Block ("structure_block", with_material(&Material::Iron, ColorId::LightGray), with_durability(-1.0F, 3600000.0F), with_no_drop()),
   Block ("jigsaw", with_material(&Material::Iron, ColorId::LightGray), with_durability(-1.0F, 3600000.0F), with_no_drop()),
   Block ("composter", with_material(&Material::Wood), with_durability(0.6F)),
   Block ("bee_nest", with_material(&Material::Wood), with_durability(0.3F)),
   Block ("beehive", with_material(&Material::Wood), with_durability(0.6F)),
   Block ("honey_block", with_material(&Material::Clay, ColorId::Adobe), with_speed_factor(0.4F), with_jump_factor(0.5F), with_not_solid()),
   Block ("honeycomb_block", with_material(&Material::Clay, ColorId::Adobe), with_durability(0.6F)),
};

} // namespace Game::Block
